//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSATool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Kraeuter_MU {
            get {
                return ((decimal)(this["Kraeuter_MU"]));
            }
            set {
                this["Kraeuter_MU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Kraeuter_IN {
            get {
                return ((decimal)(this["Kraeuter_IN"]));
            }
            set {
                this["Kraeuter_IN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Kraeuter_FF {
            get {
                return ((decimal)(this["Kraeuter_FF"]));
            }
            set {
                this["Kraeuter_FF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Kraeuter_Sinnesschaerfe {
            get {
                return ((decimal)(this["Kraeuter_Sinnesschaerfe"]));
            }
            set {
                this["Kraeuter_Sinnesschaerfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Kraeuter_Wildnisleben {
            get {
                return ((decimal)(this["Kraeuter_Wildnisleben"]));
            }
            set {
                this["Kraeuter_Wildnisleben"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Kraeuter_Pflanzenkunde {
            get {
                return ((decimal)(this["Kraeuter_Pflanzenkunde"]));
            }
            set {
                this["Kraeuter_Pflanzenkunde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Nahrung_MU {
            get {
                return ((decimal)(this["Nahrung_MU"]));
            }
            set {
                this["Nahrung_MU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Nahrung_IN {
            get {
                return ((decimal)(this["Nahrung_IN"]));
            }
            set {
                this["Nahrung_IN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Nahrung_FF {
            get {
                return ((decimal)(this["Nahrung_FF"]));
            }
            set {
                this["Nahrung_FF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Nahrung_Sinnesschaerfe {
            get {
                return ((decimal)(this["Nahrung_Sinnesschaerfe"]));
            }
            set {
                this["Nahrung_Sinnesschaerfe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Nahrung_Wildnisleben {
            get {
                return ((decimal)(this["Nahrung_Wildnisleben"]));
            }
            set {
                this["Nahrung_Wildnisleben"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Nahrung_Pflanzenkunde {
            get {
                return ((decimal)(this["Nahrung_Pflanzenkunde"]));
            }
            set {
                this["Nahrung_Pflanzenkunde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Nahrung_Ackerbau {
            get {
                return ((decimal)(this["Nahrung_Ackerbau"]));
            }
            set {
                this["Nahrung_Ackerbau"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Jagd_MU {
            get {
                return ((decimal)(this["Jagd_MU"]));
            }
            set {
                this["Jagd_MU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Jagd_IN {
            get {
                return ((decimal)(this["Jagd_IN"]));
            }
            set {
                this["Jagd_IN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Jagd_GE {
            get {
                return ((decimal)(this["Jagd_GE"]));
            }
            set {
                this["Jagd_GE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Jagd_Faehrtensuche {
            get {
                return ((decimal)(this["Jagd_Faehrtensuche"]));
            }
            set {
                this["Jagd_Faehrtensuche"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Jagd_Wildnisleben {
            get {
                return ((decimal)(this["Jagd_Wildnisleben"]));
            }
            set {
                this["Jagd_Wildnisleben"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Jagd_Tierkunde {
            get {
                return ((decimal)(this["Jagd_Tierkunde"]));
            }
            set {
                this["Jagd_Tierkunde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Jagd_Schleichen {
            get {
                return ((decimal)(this["Jagd_Schleichen"]));
            }
            set {
                this["Jagd_Schleichen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Jagd_SichVerstecken {
            get {
                return ((decimal)(this["Jagd_SichVerstecken"]));
            }
            set {
                this["Jagd_SichVerstecken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Jagd_Fernkampfwaffe {
            get {
                return ((decimal)(this["Jagd_Fernkampfwaffe"]));
            }
            set {
                this["Jagd_Fernkampfwaffe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Jagd_Scharfschuetze {
            get {
                return ((bool)(this["Jagd_Scharfschuetze"]));
            }
            set {
                this["Jagd_Scharfschuetze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Jagd_Meisterschuetze {
            get {
                return ((bool)(this["Jagd_Meisterschuetze"]));
            }
            set {
                this["Jagd_Meisterschuetze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Fischen_IN {
            get {
                return ((decimal)(this["Fischen_IN"]));
            }
            set {
                this["Fischen_IN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Fischen_KL {
            get {
                return ((decimal)(this["Fischen_KL"]));
            }
            set {
                this["Fischen_KL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Fischen_FF {
            get {
                return ((decimal)(this["Fischen_FF"]));
            }
            set {
                this["Fischen_FF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal Fischen_KK {
            get {
                return ((decimal)(this["Fischen_KK"]));
            }
            set {
                this["Fischen_KK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Fischen_FischenAngeln {
            get {
                return ((decimal)(this["Fischen_FischenAngeln"]));
            }
            set {
                this["Fischen_FischenAngeln"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Fischen_Fallenstellen {
            get {
                return ((decimal)(this["Fischen_Fallenstellen"]));
            }
            set {
                this["Fischen_Fallenstellen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool About_ManuelleEingabe {
            get {
                return ((bool)(this["About_ManuelleEingabe"]));
            }
            set {
                this["About_ManuelleEingabe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool About_CharakterKopplung {
            get {
                return ((bool)(this["About_CharakterKopplung"]));
            }
            set {
                this["About_CharakterKopplung"] = value;
            }
        }
    }
}
